version: "3.9"
services:

  trampay-backend:
    build: '.'
    ports: 
      - "3001:3001"
    command: "yarn start"
    restart: 'always'
    depends_on:
      - trampay-database
    networks: 
      - backend

  trampay-database:
    image: postgres
    restart: 'always'
    ports: 
      - '5433:5432'
    networks: 
      - backend
    environment:
      POSTGRES_DB: "${PG_DB}"
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_PASSWORD: "${PG_PASS}"

networks: 
  backend:
    driver: bridge